module.exports = {
  sydney: require('./australia-sydney.json'),
  perth: require('./australia-western-australia-perth.json'),
  rio: require('./brazil-rio-de-janeiro.json'),
  aarhus: require('./denmark-aarhus.json'),
  copenhagen: require('./denmark-copenhagen.json'),
  odense: require('./denmark-funen-odense.json'),
  aalborg: require('./denmark-jutland-aalborg.json'),
  cairo: require('./egypt-cairo.json'),
  berlin: require('./germany-berlin.json'),
  rome: require('./italy-rome.json'),
  venice: require('./italy-venice.json'),
  mexicoCity: require('./mexico-mexico-city.json'),
  pyongyang: require('./north-korea-pyongyang.json'),
  johannesburg: require('./south-africa-gauteng-johannesburg.json'),
  barcelona: require('./spain-barcelona.json'),
  madrid: require('./spain-madrid.json'),
  bern: require('./switzerland-bern.json'),
  abudhabi: require('./united-arab-emirates-abu-dhabi.json'),
  lasVegas: require('./usa-las-vegas.json'),
  losAngeles: require('./usa-los-angeles.json'),
  newYorkCity: require('./usa-new-york-city.json'),
};